'use client';

import { useActionState, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { addProperty, type FormState } from './actions';
import ImageUploader from './ImageUploader';

const INITIAL_STATE: FormState = { status: 'idle', message: '' };

const inputCls =
  'w-full px-4 py-2.5 rounded-xl border border-gray-200 text-[14px] outline-none ' +
  'focus:border-[var(--primary)] focus:ring-2 focus:ring-[#1B995420] transition-all bg-white';
const labelCls = 'block text-[12px] font-semibold text-gray-600 mb-1.5 uppercase tracking-wide';

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className={labelCls} style={{ fontFamily: 'var(--font-inter)' }}>{label}</label>
      {children}
    </div>
  );
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3
      className="col-span-full text-[11px] font-bold uppercase tracking-widest pb-2 border-b border-gray-100"
      style={{ fontFamily: 'var(--font-inter)', color: 'var(--primary)' }}
    >
      {children}
    </h3>
  );
}

function buildWaText(title: string, location: string): string {
  const t = title.trim();
  const l = location.trim();
  if (!t && !l) return '';
  if (t && l) return encodeURIComponent(`Hello! I am interested in ${t} located at ${l}.`);
  if (t)      return encodeURIComponent(`Hello! I am interested in ${t}.`);
  return           encodeURIComponent(`Hello! I am interested in a property located at ${l}.`);
}

export default function AddPropertyForm() {
  const [state, action, pending] = useActionState(addProperty, INITIAL_STATE);
  const formRef = useRef<HTMLFormElement>(null);

  // Controlled fields that drive the auto-fill
  const [title, setTitle]         = useState('');
  const [location, setLocation]   = useState('');
  const [waText, setWaText]       = useState('');
  const [waEdited, setWaEdited]   = useState(false);
  // Cloudinary upload state — URLs injected as hidden input on submit
  const [uploadedUrls, setUploadedUrls] = useState<string[]>([]);
  const [uploading, setUploading]       = useState(false);

  // Auto-generate WA text whenever title or location changes,
  // but only if the user hasn't manually overridden it.
  useEffect(() => {
    if (!waEdited) {
      setWaText(buildWaText(title, location));
    }
  }, [title, location, waEdited]);

  // Reset everything when the server action succeeds
  useEffect(() => {
    if (state.status === 'success') {
      formRef.current?.reset();
      setTitle('');
      setLocation('');
      setWaText('');
      setWaEdited(false);
      setUploadedUrls([]);
      setUploading(false);
    }
  }, [state]);

  function handleWaChange(e: React.ChangeEvent<HTMLInputElement>) {
    setWaText(e.target.value);
    // Mark as manually edited only if the user actually typed something
    // different from what auto-fill would produce
    setWaEdited(e.target.value !== buildWaText(title, location));
  }

  function handleWaRegenerate() {
    setWaEdited(false);
    setWaText(buildWaText(title, location));
  }

  const autoGenerated = !waEdited && waText === buildWaText(title, location);

  return (
    <form ref={formRef} action={action} className="space-y-8">

      {/* ── Status Banner ──────────────────────────────────────────────── */}
      {state.status === 'success' && (
        <div className="flex items-start gap-3 p-4 rounded-2xl border"
          style={{ background: '#ECFDF5', borderColor: '#86EFAC' }}>
          <span className="text-2xl mt-0.5">✅</span>
          <div>
            <p className="font-bold text-[14px]" style={{ fontFamily: 'var(--font-poppins)', color: '#166534' }}>
              {state.message}
            </p>
            {state.propertyId && (
              <Link href={`/properties/${state.propertyId}`}
                className="text-[13px] underline mt-1 inline-block"
                style={{ color: 'var(--primary)', fontFamily: 'var(--font-inter)' }}>
                View property →
              </Link>
            )}
          </div>
        </div>
      )}

      {state.status === 'error' && (
        <div className="flex items-start gap-3 p-4 rounded-2xl border"
          style={{ background: '#FEF2F2', borderColor: '#FCA5A5' }}>
          <span className="text-2xl mt-0.5">❌</span>
          <div style={{ fontFamily: 'var(--font-inter)', color: '#991B1B' }}>
            {state.message.split('\n').map((line, i) => (
              <p key={i} className={i === 0 ? 'font-semibold text-[14px]' : 'font-mono text-[12px] mt-1 break-all'}>
                {line}
              </p>
            ))}
          </div>
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 1 — Core Details
      ════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <SectionHeading>Core Details</SectionHeading>

        <Field label="Title *">
          <input
            name="title"
            type="text"
            required
            value={title}
            onChange={e => setTitle(e.target.value)}
            placeholder="e.g. Luxury 3-Bedroom Duplex in Lekki"
            className={inputCls}
            style={{ fontFamily: 'var(--font-inter)' }}
          />
        </Field>

        <Field label="Description">
          <textarea name="description" rows={4} placeholder="Full property description…"
            className={inputCls + ' resize-y'} style={{ fontFamily: 'var(--font-inter)' }} />
        </Field>

        <Field label="Price (₦) *">
          <input name="price" type="number" required min="0" placeholder="e.g. 120000000"
            className={inputCls} style={{ fontFamily: 'var(--font-inter)' }} />
        </Field>

        <Field label="Price Period">
          <select name="price_period" className={inputCls} style={{ fontFamily: 'var(--font-inter)' }}>
            <option value="">None (for sale / land)</option>
            <option value="/yr">/yr — per year</option>
            <option value="/month">/month — per month</option>
            <option value="/night">/night — short let</option>
          </select>
        </Field>

        <Field label="Status *">
          <select name="status" required className={inputCls} style={{ fontFamily: 'var(--font-inter)' }}>
            <option value="FOR SALE">FOR SALE</option>
            <option value="FOR RENT">FOR RENT</option>
            <option value="SHORT LET">SHORT LET</option>
            <option value="OFF-PLAN">OFF-PLAN</option>
            <option value="LAND FOR SALE">LAND FOR SALE</option>
          </select>
        </Field>

        <Field label="Property Type *">
          <select name="property_type" required className={inputCls} style={{ fontFamily: 'var(--font-inter)' }}>
            <option value="duplex">Duplex</option>
            <option value="apartment">Apartment</option>
            <option value="penthouse">Penthouse</option>
            <option value="bungalow">Bungalow</option>
            <option value="terrace">Terrace</option>
            <option value="commercial">Commercial</option>
            <option value="land">Land</option>
          </select>
        </Field>
      </div>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 2 — Location
      ════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <SectionHeading>Location</SectionHeading>

        <Field label="Full Location *">
          <input
            name="location"
            type="text"
            required
            value={location}
            onChange={e => setLocation(e.target.value)}
            placeholder="e.g. Lekki Phase 1, Lagos State"
            className={inputCls}
            style={{ fontFamily: 'var(--font-inter)' }}
          />
        </Field>

        <Field label="Location Key *">
          <select name="location_key" required className={inputCls} style={{ fontFamily: 'var(--font-inter)' }}>
            <option value="lagos">Lagos</option>
            <option value="abuja">Abuja</option>
            <option value="port-harcourt">Port Harcourt</option>
          </select>
        </Field>
      </div>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 3 — Specs
      ════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        <SectionHeading>Property Specs</SectionHeading>

        <Field label="Bedrooms">
          <input name="bedrooms" type="number" min="0" defaultValue={0}
            className={inputCls} style={{ fontFamily: 'var(--font-inter)' }} />
        </Field>

        <Field label="Bathrooms">
          <input name="bathrooms" type="number" min="0" defaultValue={0}
            className={inputCls} style={{ fontFamily: 'var(--font-inter)' }} />
        </Field>

        <Field label="Size (sqm)">
          <input name="sqm" type="number" min="0" defaultValue={0}
            className={inputCls} style={{ fontFamily: 'var(--font-inter)' }} />
        </Field>
      </div>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 4 — Features & Amenities
      ════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <SectionHeading>Features &amp; Amenities</SectionHeading>

        <Field label="Key Features (comma-separated)">
          <input name="features" type="text"
            placeholder="Fitted Kitchen, Boys Quarters, Spacious Garden, CCTV"
            className={inputCls} style={{ fontFamily: 'var(--font-inter)' }} />
          <p className="text-[11px] text-gray-400 mt-1.5" style={{ fontFamily: 'var(--font-inter)' }}>
            Each item separated by a comma becomes a bullet point.
          </p>
        </Field>

        <Field label="Amenities (comma-separated labels or JSON)">
          <textarea name="amenities" rows={3}
            placeholder={'Pool, Gym, Security, Parking\nor JSON: [{"i":"🏊","l":"Pool"},{"i":"🏋️","l":"Gym"}]'}
            className={inputCls + ' resize-y font-mono text-[12px]'} />
          <p className="text-[11px] text-gray-400 mt-1.5" style={{ fontFamily: 'var(--font-inter)' }}>
            Plain labels get a 📌 icon. Use JSON for custom emojis.
          </p>
        </Field>
      </div>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 5 — Media
      ════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 gap-5">
        <SectionHeading>Media</SectionHeading>

        <Field label="Images">
          {/* Hidden input carries the comma-separated URLs to the server action */}
          <input
            type="hidden"
            name="images"
            value={uploadedUrls.join(',')}
          />
          <ImageUploader
            onChange={setUploadedUrls}
            onUploadingChange={setUploading}
          />
        </Field>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          <Field label="TikTok Video ID">
            <input name="tiktok_id" type="text" placeholder="e.g. 7612758048372886802"
              className={inputCls} style={{ fontFamily: 'var(--font-inter)' }} />
            <p className="text-[11px] text-gray-400 mt-1.5" style={{ fontFamily: 'var(--font-inter)' }}>
              The number at the end of the TikTok URL — not the full link.
            </p>
          </Field>

          <Field label="Gradient (CSS)">
            <input name="gradient" type="text"
              defaultValue="linear-gradient(135deg,#1B9954,#0F5E36)"
              placeholder="linear-gradient(135deg,#1B9954,#0F5E36)"
              className={inputCls + ' font-mono text-[12px]'} />
          </Field>
        </div>
      </div>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 6 — WhatsApp & Flags
      ════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <SectionHeading>WhatsApp &amp; Visibility</SectionHeading>

        <Field label="WhatsApp Pre-filled Message (URL-encoded)">
          <div className="relative">
            <input
              name="whatsapp_text"
              type="text"
              value={waText}
              onChange={handleWaChange}
              placeholder="Auto-generated from title and location…"
              className={inputCls + ' font-mono text-[12px] pr-24'}
            />
            {/* Regenerate button — only shown when user has overridden */}
            {waEdited && (
              <button
                type="button"
                onClick={handleWaRegenerate}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-[11px] font-semibold px-2.5 py-1 rounded-lg transition-colors"
                style={{ background: '#ECFDF5', color: 'var(--primary)', fontFamily: 'var(--font-inter)' }}
              >
                ↺ Reset
              </button>
            )}
          </div>
          <p className="text-[11px] mt-1.5 flex items-center gap-1.5" style={{ fontFamily: 'var(--font-inter)', color: autoGenerated && waText ? 'var(--primary)' : '#9ca3af' }}>
            {autoGenerated && waText
              ? <><span>✦</span> Auto-generated from title &amp; location. Edit to customise.</>
              : waEdited
              ? <><span style={{ color: '#FFB703' }}>✎</span> <span style={{ color: '#92400e' }}>Manually edited — click ↺ Reset to restore auto-fill.</span></>
              : 'Will be generated once you enter a title and/or location.'}
          </p>
        </Field>

        <div className="flex flex-col gap-4 pt-2">
          <label className="flex items-center gap-3 cursor-pointer select-none">
            <div className="relative">
              <input type="checkbox" name="featured" className="sr-only peer" />
              <div className="w-10 h-6 rounded-full bg-gray-200 peer-checked:bg-[var(--primary)] transition-colors" />
              <div className="absolute top-0.5 left-0.5 w-5 h-5 rounded-full bg-white shadow peer-checked:translate-x-4 transition-transform" />
            </div>
            <div>
              <span className="font-semibold text-[13px]" style={{ fontFamily: 'var(--font-poppins)', color: 'var(--dark-text)' }}>Featured</span>
              <p className="text-[11px] text-gray-400" style={{ fontFamily: 'var(--font-inter)' }}>Shows on homepage Featured Listings grid</p>
            </div>
          </label>

          <label className="flex items-center gap-3 cursor-pointer select-none">
            <div className="relative">
              <input type="checkbox" name="published" defaultChecked className="sr-only peer" />
              <div className="w-10 h-6 rounded-full bg-gray-200 peer-checked:bg-[var(--primary)] transition-colors" />
              <div className="absolute top-0.5 left-0.5 w-5 h-5 rounded-full bg-white shadow peer-checked:translate-x-4 transition-transform" />
            </div>
            <div>
              <span className="font-semibold text-[13px]" style={{ fontFamily: 'var(--font-poppins)', color: 'var(--dark-text)' }}>Published</span>
              <p className="text-[11px] text-gray-400" style={{ fontFamily: 'var(--font-inter)' }}>Visible to public (unpublish to hide without deleting)</p>
            </div>
          </label>
        </div>
      </div>

      {/* ── Submit ─────────────────────────────────────────────────────── */}
      <div className="pt-4 flex items-center gap-4 flex-wrap">
        <button
          type="submit"
          disabled={pending || uploading}
          className="flex items-center gap-2 font-bold text-[15px] px-10 py-4 rounded-full text-white transition-all hover:-translate-y-0.5 disabled:opacity-60 disabled:cursor-not-allowed disabled:translate-y-0"
          style={{
            fontFamily: 'var(--font-poppins)',
            background: 'linear-gradient(135deg,var(--primary),var(--dark))',
            boxShadow: '0 6px 20px rgba(27,153,84,0.35)',
          }}
        >
          {uploading ? (
            <>
              <svg className="animate-spin" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <circle cx="12" cy="12" r="10" strokeOpacity="0.25" />
                <path d="M12 2a10 10 0 0110 10" />
              </svg>
              Uploading images…
            </>
          ) : pending ? (
            <>
              <svg className="animate-spin" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <circle cx="12" cy="12" r="10" strokeOpacity="0.25" />
                <path d="M12 2a10 10 0 0110 10" />
              </svg>
              Saving…
            </>
          ) : (
            '＋ Add Property'
          )}
        </button>

        <Link href="/properties"
          className="text-[14px] font-semibold transition-opacity hover:opacity-70"
          style={{ fontFamily: 'var(--font-inter)', color: 'var(--gray)' }}>
          ← Back to Properties
        </Link>
      </div>
    </form>
  );
}
